# This is a basic workflow to help you get started with Actions

name: Release Backend Staging

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: innovantics/eximma_api:staging
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Api/Dockerfile
    - name: Deployment
      uses: appleboy/ssh-action@master
      env:
        DB_PASS: ${{ secrets.DB_PASS }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: DB_PASS
        script: |
          cd ~/publish
          docker-compose stop eximma_api_staging
          docker-compose pull eximma_api_staging
          DB_PASSWORD=$DB_PASS docker-compose up -d eximma_api_staging
          exit
    - name: Deployment Notification
      uses: act10ns/slack@v1
      env:
        SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: "#eximma"
      if: always() 
